[tool.poetry]
name = "oc_ocdm"
version = "3.1.0"
description = "Object mapping library for OpenCitations, OCDM 2.0.1 compliant."
authors = [
    "Silvio Peroni <essepuntato@gmail.com>",
    "Marilena Daquino <marilena.daquino2@unibo.it>",
    "Fabio Mariani <fabio.mariani6@studio.unibo.it>",
    "Simone Persiani <iosonopersia@gmail.com>"
]
readme = "README.md"
license = "ISC"
homepage = "http://opencitations.net"
# repository = "https://github.com/opencitations/oc_ocdm"
# documentation = "https://oc_ocdm.github.io"
keywords = ["opencitations", "openscience", "datamodel", "mapping"]

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Natural Language :: English",
    "Natural Language :: Italian",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Archiving",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.7"
rdflib = "^5.0.0"
PyShEx = "^0.7.20"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.782"
Sphinx = "^3.3.1"
sphinx_rtd_theme = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
test = 'scripts:test'
clean_info_dir = 'scripts:clean_info_dir'
